### PR TITLE
use SNI for TLS connections

### LINKED ISSUE #347: Cannot open TLS connections to servers that require SNI
Any attempt to connect to a server that requires SNI results in handshake failure -- for instance it's impossible to connect to `https://www.clojure.org` because of this.

We need to set the SNI with `SSL_set_tlsext_host_name` when creating the SSL socket with `SSL_new`; however, this is created in  `___device_tcp_client_setup_from_sockaddr` and there doesn't seem to be an obvious way to get the actual name server there.

### PR DESCRIPTION
**Pull request by vyzo**
Fixes #347

### CODE REVIEW

**Comment by vyzo** [comment]
should be ready for review now

**Comment by feeley** [comment]
When is server_name_p released?

**Comment by vyzo** [comment]
It is released in `___device_tcp_client_setup_from_sockaddr`.
Maybe I missed some paths though and this can leak.

**Comment by vyzo** [comment]
It can leak indeed, if `___SCMOBJ_to_sockaddr` fails for instance; let me try and fortify.

**Comment by vyzo** [comment]
It might be better to release it in `___os_device_tcp_client_open` so that the reference is only borrowed and we don't ahve to duplicate error path releases.
Fixing.

**Pull request merged**
