### PR TITLE
Simplify CI patterns for code checkout and MSYS/MinGW invocation

### PR DESCRIPTION
**Pull request by daviwil**
@eine left some helpful tips in issue #590, this PR implements them to simplify our CI jobs further.  I'm also adding `texinfo` as a dependency to be installed for Windows builds so that we can build `info` files in `make doc`.

### CODE REVIEW

**Comment by eine** [comment]
@daviwil, it seems that `tar` might be installed on the default virtual environment, but not in MSYS2. Hence, when removing the path inheritance, it is not found. This is strange to me, as I'd expect `tar` to be part of the base MSYS2. Nevertheless, it should be fixable by adding `tar` to `install:`.

**Comment by daviwil** [comment]
@eine Thanks!  That's probably the issue I had run into before.  I'll bet `inherit` caused the `tar` from the Git for Windows distribution to get picked up in `PATH`.

**Comment by eine** [comment]
JFYTK, the default `tar` in the virtual environment is kind of broken: actions/virtual-environments#282. That's why 7z is used in setup-msys2: numworks/setup-msys2#26.

**Comment by daviwil** [comment]
Good to know, thanks!

**Pull request merged**
