### PR TITLE
Fix for issue #659

### PR DESCRIPTION
**Pull request by SamuelYvon**
Removed reordering when we are creating the bindings for `let*`.  One can verify with the provided example of #659 that the `_300` variable is not reordered.

### CODE REVIEW

**Comment by feeley** [comment]
Thank you for your contribution.  The checks (`make check`) don't succeed and this is a requirement for accepting the PR.  Could you please fix this?

**Comment by SamuelYvon** [comment]
I'll investigate later; the only test that fails is the first one (`test1`). Removing it and running `make check` shows `All tests succeeded`

**Comment by gambiteer** [comment]
I wondered whether the code in the interpreter and this new code is the same.

**Comment by SamuelYvon** [comment]
It seems like this change breaks inlining... Back to drawing board.

**Comment by fare** [comment]
The error is as follows:
```
make[1]: Entering directory '/d/a/gambit/gambit/tests'
------------ TEST 1 (debugging support)
../gsi/gsi.exe -:~~bin=../bin,~~lib=../lib,~~include=../include -f debug.scm > test1.out
diff test1.ok test1.out && rm -f test1.out
262,264c262,265
< #return(##cprc-prc 7) : ($code args i inner-rte j n proc rte)
< #return(##cprc-prc 8) : ($code end i inner-rte j k keys left rest? rte)
< #return(##cprc-prc 9) : ($code args entry-hook exec proc rte)
make[1]: *** [makefile:119: test1] Error 1
---
make: *** [makefile:208: check] Error 2
> #return(##cprc-prc 7) : ($code args inner-rte n proc reject-illegal-dsssl-parameter-list? rte)
> #return(##cprc-prc 8) : ($code args i inner-rte j n proc reject-illegal-dsssl-parameter-list? rte)
> #return(##cprc-prc 9) : ($code end i inner-rte j k keys left rest? rte)
> #return(##cprc-prc 10) : ($code args entry-hook exec proc rte)
make[1]: Leaving directory '/d/a/gambit/gambit/tests'
Error: Process completed with exit code 2.
```
It looks like some execution trace has changed. The change might quite possibly be legal and expected, after the compiler was changed to handle letrec* differently. How do I tell? And how do I get to run all the tests without stopping at the first error?

**Comment by gambiteer** [comment]
make -i check

**Comment by gambiteer** [comment]
I tried this version of the patch:
```
diff --git a/gsc/_ptree1.scm b/gsc/_ptree1.scm
index 71d68bf3..3d992653 100644
--- a/gsc/_ptree1.scm
+++ b/gsc/_ptree1.scm
@@ -1896,8 +1896,9 @@
             (let* ((var (car l))
                    (val (val-of var)))
               (if (or (prc? val)
-                      (not (varset-intersects? (bound-free-variables val)
-                                               vars-set)))
+                      (not (or *?
+                               (varset-intersects? (bound-free-variables val)
+                                                   vars-set))))
                 (loop1 (cdr l)
                        (cons var vars-b)
                        (cons val vals-b)
```
and it passed `make check` no problems, and it fixed issue #659.

I don't understand this code very well at all, but I'm included to push this.  Any thoughts?

**Comment by gambiteer** [comment]
I pushed your fix as is.

**Comment by fare** [comment]
It seems to me that the failing regression test caused by the fix is that some bytecode changed... which it probably should if the code uses letrec* which is now fixed. So maybe the fix actually works and the test must be changed? Who understands the failing test? Can we get this fixed? It really affects gerbil coding style badly.

**Comment by SamuelYvon** [comment]
The code was pushed by @gambiteer directly, so your issue must come from somewhere else. See commit https://github.com/gambit/gambit/commit/47f2eb7feb5deae94c0b96f5a50310d978e120ae. However issue #659 lists the issue as open and mentions that its still a problem. Maybe the commit was reverted?

**Comment by fare** [comment]
Yes, it was immediately reverted in d1a6c6bf5ea019731c4264ed7a91c0386659a989 for breaking regression tests... that I believe might just need to be updated.

**Comment by SamuelYvon** [comment]
I see. The code has significantly changed from a quick glance, let me take a second go at it.

**Comment by fare** [comment]
Force-push? Ouch, commit wars are bad... also, I don't see a fix in master currently. Why close? Or is the closing a subtle side-effect of the force-push?

**Pull request closed without merging**
