### PR TITLE
Universal backend: add continuation ops and fixnum ops

### PR DESCRIPTION
**Pull request by feeley**

### CODE REVIEW

**Comment by gambiteer** [comment]
Does this mean that we can run the unit tests in the universal backend now?

On Mar 24, 2020, at 4:49 PM, Marc Feeley <notifications@github.com<mailto:notifications@github.com>> wrote:

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/gambit/gambit/pull/511

Commit Summary

  *   Universal backend: add continuation ops and fixnum ops

File Changes

  *   M doc/gambit.txi<https://github.com/gambit/gambit/pull/511/files#diff-7e4c006019aae4b42168715103ae3cb1> (12)
  *   M gsc/_t-univ-1.scm<https://github.com/gambit/gambit/pull/511/files#diff-117095dd708a9f7e2c2ad3a17d29acef> (49)
  *   M gsc/_t-univ-4.scm<https://github.com/gambit/gambit/pull/511/files#diff-45201813261fe405ab6ef4dd739282d7> (60)
  *   M gsi/main.scm<https://github.com/gambit/gambit/pull/511/files#diff-0bdf91415a62fc76caa2b35394f5412d> (44)
  *   M lib/_std.scm<https://github.com/gambit/gambit/pull/511/files#diff-a5c6a156b6c4358bc110c2911f8b7c92> (4)
  *   M lib/_univlib.scm<https://github.com/gambit/gambit/pull/511/files#diff-9d790f7be41e9e08f9d2a7d397b63c5c> (81)
  *   M tests/run-unit-tests.scm<https://github.com/gambit/gambit/pull/511/files#diff-496a3326a53c9e8171465585b1daa5f7> (17)

Patch Links:

  *   https://github.com/gambit/gambit/pull/511.patch
  *   https://github.com/gambit/gambit/pull/511.diff

**Comment by feeley** [comment]
Yes.  In fact many unit tests now pass...

```
% cd tests
% ./run-unit-tests.scm -js
...
[214| 31] 100% ################ 840.6s
FAILED 31 UNIT TESTS OUT OF 245 (12.7%)
```

Many of the failing tests are for "advanced" features such as networking whose implementation is harder.

**Comment by gambiteer** [comment]
On Mar 24, 2020, at 6:58 PM, Marc Feeley <notifications@github.com<mailto:notifications@github.com>> wrote:


./run-unit-tests.scm -js

Here’s what I get with GitHub head when I try this:

[Bradleys-Mac-mini:~/programs/gambit/tests] lucier% ./run-unit-tests.scm -js
[  0|  0]   0% ................  .0s 00-check/check_eq.scmenv: node: No such file or directory

*** FAILED 00-check/check_eq.scm WITH EXIT CODE HI=127 LO=0
[  0|  1]   0% ................ 1.0s 00-check/check_eqp.scmenv: node: No such file or directory

*** FAILED 00-check/check_eqp.scm WITH EXIT CODE HI=127 LO=0
[  0|  2]   0% ................ 2.0s 00-check/check_equalp.scmenv: node: No such file or directory

Etc.  I made _gambit.js in lib.

**Comment by feeley** [comment]
`brew install node`

**Comment by feeley** [comment]
After a `git pull;make` this should work too:

```
% make _gambit.js
% gsc/gsc -:= -target js -exe -o webapp.js webapp.scm
% open webapp.html
% cat webapp.scm
(declare (extended-bindings))
(define (document.write html)
  (##inline-host-statement "document.write(g_scm2host(@1@));" html))
(document.write "<h1>Hello world!</h1>")
% cat webapp.html
<!doctype html>
<html>

  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>webapp</title>
  </head>

  <body>
    <script type="text/javascript" src="webapp.js"></script>
  </body>

</html>
```

**Pull request merged**
