### PR TITLE
Expand misc/bench.tgz to bench.

### PR DESCRIPTION
**Pull request by gambiteer**
I think it's time to have the bench directory be expanded like any other directory.

### CODE REVIEW

**Comment by feeley** [comment]
Nice idea, but this is incomplete.  A "make dist" and "make dist-devel" will fail to copy the bench directory.  For this to work the bench directory and its subdirectories need to have a makefile.in file that does the right thing on a "make dist".  See for example the makefile.in files in prebuilt and prebuilt/macosx .  Also, in the main makefile.in file the bench directory has to be added to the SUBDIRS variable.  This would be a good opportunity to add to the benchmark's makefile some different targets for common benchmark settings.

**Comment by gambiteer** [comment]
OK, I just spent 30 minutes on this and I've concluded that "do what's 
in prebuilt and its subdirectories" will not suffice to school me in the 
mysteries of makefiles necessary to complete this task.

So I'm tempted to say "screw it".

Brad

**Comment by gambiteer** [comment]
Here's a specific problem:

make[2]: Entering directory 
'/home/lucier/programs/gambit/gambit-gambiteer/bench/num-iters'
make[2]: *** No rule to make target 'dist'.  Stop.

I have

heine:~/programs/gambit/gambit-gambiteer> diff 
bench/num-iters/makefile.in prebuilt/macosx/makefile.in
5c5
< herefromroot = bench/num-iters
---
 > herefromroot = prebuilt/macosx
71,76c71,74
< RCFILES = \
< makefile.in\
< num-iters-1.scm\
< num-iters-int.scm\
< num-iters.scm\
< one-iter.scm
---
 > RCFILES = makefile.in build build-phase2.in remote-shell \
 > InstallationCheck.in postflight.in \
 > gambit.ai gambit.tif gambit.pmproj.in \
 > welcome.html.in readme.html.in conclusion.html.in uninstall-gambit.in
86a85,87
 >
 > prebuilt:
 > 	PATH="$(rootfromhere)/gsi:$$PATH" ../remote-connect macosx "" 
"(define tmpdir \"gambtmp1\")(define gambit-dist 
\"$(PACKAGE_TARNAME)\")(define timeout 2000)(ssh timeout (string-append 
\"sudo rm -rf \" tmpdir \";mkdir \" tmpdir \";\"))(scp-to timeout 
(string-append \"$(rootfromhere)/\" gambit-dist \".tgz\") (string-append 
tmpdir \"/.\"))(ssh timeout (string-append \"cd \" tmpdir \";tar zxf \" 
gambit-dist \".tgz;cd \" gambit-dist \";sudo 
$(herefromroot)/build\"))(scp-from timeout (string-append tmpdir \"/\" 
gambit-dist \"/$(PACKAGE_TARNAME)-*\") \"$(rootfromhere)\")"


and


heine:~/programs/gambit/gambit-gambiteer> diff bench/makefile.in 
prebuilt/makefile.in
5c5
< herefromroot = bench
---
 > herefromroot = prebuilt
7c7
< SUBDIRS = num-iters prefix src suffic summarize sys
---
 > SUBDIRS = macosx windows
71c71
< RCFILES = makefile.in README
---
 > RCFILES = makefile.in README remote-connect
82a83,86
 > prebuilt-pre:
 >
 > prebuilt-post:
 >
141c145
< all-recursive bootstrap-recursive install-recursive 
uninstall-recursive select-gen-for-commit-recursive 
deselect-gen-for-commit-recursive mostlyclean-recursive clean-recursive 
distclean-recursive bootclean-recursive realclean-recursive 
rc-setup-recursive dist-recursive dist-devel-recursive bench-recursive:
---
 > all-recursive bootstrap-recursive install-recursive 
uninstall-recursive select-gen-for-commit-recursive 
deselect-gen-for-commit-recursive mostlyclean-recursive clean-recursive 
distclean-recursive bootclean-recursive realclean-recursive 
rc-setup-recursive dist-recursive dist-devel-recursive prebuilt-recursive:
232a237,242
 >
 > prebuilt: prebuilt-post
 >
 > prebuilt-post: prebuilt-recursive
 >
 > prebuilt-recursive: prebuilt-pre



So where do I put something in so "make dist" works in bench/num-iters?

Brad

**Comment by gambiteer** [comment]
Got that one.  Going forward ...

**Comment by gambiteer** [comment]
In bench/sys there are a lot of subdirectories that I want built (I 
think) with "make dist" but I want them to be empty, i.e., I don't want 
to put a makefile in them, etc. (I think).

What do I put into bench/sys/makefile.in to do this?

Brad

**Comment by gambiteer** [comment]
I think I failed in the bench/sys/ subdirectory, but I can't see a parallel structure in an existing subdirectory.

Please look at my second commit and see what you think.  It might take just a small fix to make it right.

Brad

**Comment by gambiteer** [comment]
"make dist" now works, I think.  The last change is ugly.

**Comment by gambiteer** [comment]
The better advice would have been to compare prebuilt/makefile.in and tests/makefile.in, which I'm doing just now.

**Comment by feeley** [comment]
Ah yes that is true... the tests subdirectory has a subdirectory tree (unit-tests) without makefiles... sorry about that.

**Comment by gambiteer** [comment]
Yes, but it still doesn't have any flipping empty directories that you want to have in the distribution, presumably without cleaning them first.

Please, Marc, I've never done a makefile before, and you want my first one to be one with six different '*clean' targets? Good grief!

**Comment by feeley** [comment]
ok, let me take a look (tomorrow)

**Pull request closed without merging**
