### PR TITLE
Store output of 'make dist-boot' as artifact, build with processor count

### PR DESCRIPTION
**Pull request by daviwil**
This change is the first step toward faster PR builds.  It uploads the output of `make dist` as an artifact called `gambit-dist.tgz` that can be downloaded from the latest successful CI build on `master` and applied to `boot/` in PR runs.  I'm almost done updating [`daviwil/download-gambit`](https://github.com/daviwil/download-gambit) to support downloading this artifact.

### CODE REVIEW

**Comment by feeley** [comment]
With commit 551edec8cb3be3fc993e83579df8e80495d2ff63 you can now do `make dist-boot` to create `boot.tgz` which can be unpacked to create the `boot` directory.  That will simplify the bootstrap procedure and is a logical name for that artifact (as suggested by @lassik).

**Comment by daviwil** [comment]
Now that I've got a successful build with the new `boot.tgz`, I'll test a PR workflow that uses it to speed up the build.  Let's hold off merging this until I've verified that it works.

**Comment by lassik** [comment]
> With commit [551edec](https://github.com/gambit/gambit/commit/551edec8cb3be3fc993e83579df8e80495d2ff63) you can now do `make dist-boot` to create `boot.tgz` which can be unpacked to create the `boot` directory.

Thank you very much for making this!

**Comment by daviwil** [comment]
Whoa, I dunno what magit did, but it closed this PR on my behalf.  Can you reopen it @feeley?

**Comment by daviwil** [comment]
Phew, OK, I was able to reopen it once I fixed the branch.  I dunno what keybinding I hit to make it delete my branch and push it immediately!

**Comment by daviwil** [comment]
@feeley So somehow the culprit is having `PATH` inheritance turned on in msys2.  When I turn that off, I see a lot of messages related to `findstr` any time `gambuild-C.bat` is executed:

```
------------ TEST 6 (link and execute the code generated)
rm -f mix_.c mix.o mix_.o mix.exe
../gsc/gsc.exe -:~~bin=../bin,~~lib=../lib,~~include=../include -f -warnings -c mix.scm
../gsc/gsc.exe -:~~bin=../bin,~~lib=../lib,~~include=../include -f -warnings -o mix.exe -exe mix.c
'findstr' is not recognized as an internal or external command, operable program or batch file.
'findstr' is not recognized as an internal or external command, operable program or batch file.
'findstr' is not recognized as an internal or external command, operable program or batch file.
'findstr' is not recognized as an internal or external command, operable program or batch file.
'findstr' is not recognized as an internal or external command, operable program or batch file.
```

However, it seems that _not_ finding `findstr` prevents the failures from occuring in `make ut`.  I'll keep investigating why this is happening but I think for this PR is safe to merge, provided that you think the `#undef HAVE_CLOCK_GETTIME` approach is OK for removing the `libwinpthread-1.dll` dependency.

**Comment by feeley** [comment]
I have merged the PR so we can move forward.  However the `#undef HAVE_CLOCK_GETTIME` is a bit hackish, so we should find a better place to disable it (`configure` is the right place but what should be detected to disable it?).  Also, I would expect that for a typical developer on Windows the PATH is inherited, so we should eventually execute the CI with inheritance when the issue is fully understood and resolved.

**Comment by daviwil** [comment]
We could probably just `#undef` it after we see `$ENABLE_THREAD_SYSTEM` equal to `win32` in `configure` since that should be fair evidence that the user doesn't want to link to `libwinpthread`.  I'll experiment with a fix.

Regarding the path inheritance issue, I suspect it's some other kind of environmental issue that's causing unexpected behavior, so I'll keep poking at that problem here and there when I have time.

**Pull request merged**
