### PR TITLE
Add ~~execdir to refer to current executable's directory

### PR DESCRIPTION
**Pull request by feeley**

### CODE REVIEW

**Comment by lassik** [comment]
Implements #569 

Thanks for the very quick turnaround!

The current PR refers to the executable directory. Is that the best alternative? If Gambit is installed using things like `--prefix=/usr/local/Gambit` or `--prefix=$HOME/.local` then the `gsc` and `gsi` go into `bin/`. This would make `~~execdir` point to `/usr/local/Gambit/bin` or `$HOME/.local/bin` instead of `/usr/local/Gambit` or `$HOME/.local`. Is the intent to use `gsi -:~~execdir/..` in this scenario?

**Comment by feeley** [comment]
Yes that is the idea.  `~~execdir` is the directory containing the executable (`gsi` in this case) and in a typical installation it is in a `bin` directory that is in the same directory as the `lib`, `include`, etc directories.

**Comment by lassik** [comment]
Does that mean `./configure --enable-gambitdir=~~execdir/..` would get us the flexibility we want for the CI builds?

Does the current implementation in this PR get the `realpath()` of the executable filename?

**Comment by feeley** [comment]
No it doesn't get the `realpath()`.  That is a separate operation.

@daviwil I have merged the PR.  So let's start using this in the CI.

**Comment by daviwil** [comment]
Yep, was just about to try it in my personal CI build.  After the initial CI PR is merged I'll send a separate PR for building and uploading usable artifacts using `~~execdir` and `--enable-shared-host`.

**Comment by lassik** [comment]
We should add a note in the manual that people probably want `~~execdir/..` in the common case.

Are the tildes `~~` written in the `./configure --enable-gambitdir=` option by the way?

**Comment by lassik** [comment]
What happens if gambitdir is relative instead of absolute?

**Comment by feeley** [comment]
A relative gambitdir, as in `gsi -:=some/relative/path` is resolved using the CWD at the time when `gsi` started.

I don't think `-:=~~execdir/..` should be the default, because on some OSes the `lib`, `bin`, `include`, etc directories aren't installed in the same directory.

**Comment by lassik** [comment]
> I don't think `-:=~~execdir/..` should be the default, because on some OSes the `lib`, `bin`, `include`, etc directories aren't installed in the same directory.

Agreed that it shouldn't be the default `./configure` option. But we should use it for the CI artifacts which are downloadable by people who follow pre-release Gambit snapshots, right?

**Comment by feeley** [comment]
Agreed... because this will probably avoid grief in typical situations.

**Pull request merged**
