### PR TITLE
Implement SRFI 219 (Define higher-order lambda)

### PR DESCRIPTION
**Pull request by lassik**
https://srfi.schemers.org/srfi-219/srfi-219.html

This implementation doesn't work because the syntax-rules macro cannot use the renamed `native-define` at the expansion site. There's probably a way to implement it (perhaps using `define-macro`). Note that the SRFI exports a `define` which shadows / conflicts with the native `define` from the `(scheme base)` library.

### CODE REVIEW

**Comment by feeley** [comment]
I'm not sure what issue you are having but probably the best thing is to use `##define` as the "native `define`".

**Comment by lassik** [comment]
It works! Tests pass.

**Comment by lassik** [comment]
Should `219.scm` and/or `219#.scm` be made?

**Comment by feeley** [comment]
Yes that would be best.

**Comment by lassik** [comment]
How is the naming conflict between the `##` version of `define` and the 219 version of `define` handled in them? They cannot place the new `define` in the `##` namespace.

**Comment by gambiteer** [comment]
This is cool.  I look forward to it working.  Brad

**Comment by lassik** [comment]
I tried to implement using namespaces by following the example of SRFI 26 (`cut`/`cute`), but it doesn't work. I get the error:

```
$ gsi lib/
> (import (srfi 219))
> (define ((foo a) b) (string-append a b))
*** ERROR IN (stdin)@2.2 -- Unbound variable: srfi/219#define
```

**Comment by feeley** [comment]
The problem is the file `219.sld` which lacks the definition of the `define` macro.  It should be:

```
(define-library (srfi 219)
  (export define)
  (include "219#.scm"))
```

**Comment by lassik** [comment]
The latest commit fixes the problem, and now passes tests and works in `gsi` scripts and REPL.

`gsc -exe foo.scm` works when `foo.scm` is:

```scheme
(import (srfi 219))
(define ((greet-with-prefix prefix) suffix)
  (string-append prefix " " suffix))
(define greet (greet-with-prefix "hello"))
(display (greet "world"))
(newline)
```

but the compiled executable doesn't work (exit code 70 with no error message; `-:d+` `-:d-` `-:dc` `-:dr` do not show an error either).

**Comment by feeley** [comment]
Did you compile with `-nopreload`? That's typically the problem...

**Comment by lassik** [comment]
`gsc -exe -nopreload foo.scm` solves the problem.

**Comment by feeley** [comment]
Great!

**Pull request merged**
