### PR TITLE
Add --enable-gambitdir=...

### PR DESCRIPTION
**Pull request by feeley**
Add --enable-gambitdir=... to bind ~~ to a specific path, possibly relative to the user's $HOME

### CODE REVIEW

**Comment by lassik** [comment]
I'll rebase my cirrus branch on top of this.

**Comment by lassik** [comment]
How do you give the `$HOME`-relative gambitdir?

**Comment by feeley** [comment]
OK.  I was waiting for the PR to pass CI.  But it should work...

For the Cirrus build artifacts, you could do the following:

```
% ./configure --prefix=$HOME/.gambit_scheme/<hash> --enable-gambitdir=~/.gambit_scheme/<hash> --enable-single-host <etc..>
% make
% make install
% ln -s ~/.gambit_scheme/<hash> ~/.gambit_scheme/current
% tar cf gambit-<hash>.tar ~/.gambit_scheme/<hash>
```

That way, the `~/.gambit_scheme/current` will be a symbolic link pointing to the latest Gambit installed.  The user then simply has to have `~/.gambit_scheme/current/bin` in their shell's PATH to use Gambit, and they don't have to change anything if they "upgrade" to another "tar release".

**Comment by lassik** [comment]
> OK. I was waiting for the PR to pass CI.

I thought Travis is broken at the moment since my last PR failed the Mac build. But maybe it was an intermittent failure.

> For the Cirrus build artifacts, you could do the following:
> 
> ```
> % ./configure --prefix=$HOME/.gambit_scheme/<hash> --enable-gambitdir=~/.gambit_scheme/<hash> --enable-single-host <etc..>
> ```

Is the `~` support the only practical difference between `--prefix` and `--enable-gambitdir`? In other words, would it be better to detect whether the prefix begins with `$HOME`, and if so, remove it for gambitdir? That way a separate configure flag would not be needed.

With the current approach, prefix and gambitdir can be set to completely unrelated values. Would that break something / is there a use case for that?

> ```
> % ln -s ~/.gambit_scheme/<hash> ~/.gambit_scheme/current
> % tar cf gambit-<hash>.tar ~/.gambit_scheme/<hash>
> ```
> 
> That way, the `~/.gambit_scheme/current` will be a symbolic link pointing to the latest Gambit installed. The user then simply has to have `~/.gambit_scheme/current/bin` in their shell's PATH to use Gambit, and they don't have to change anything if they "upgrade" to another "tar release".

That sounds very nice!

**Comment by feeley** [comment]
> > OK. I was waiting for the PR to pass CI.
> 
> I thought Travis is broken at the moment since my last PR failed the Mac build. But maybe it was an intermittent failure.
> 
> > For the Cirrus build artifacts, you could do the following:
> > ```
> > % ./configure --prefix=$HOME/.gambit_scheme/<hash> --enable-gambitdir=~/.gambit_scheme/<hash> --enable-single-host <etc..>
> > ```
> 
> Is the `~` support the only practical difference between `--prefix` and `--enable-gambitdir`? In other words, would it be better to detect whether the prefix begins with `$HOME`, and if so, remove it for gambitdir? That way a separate configure flag would not be needed.
> 
> With the current approach, prefix and gambitdir can be set to completely unrelated values. Would that break something / is there a use case for that?

That's not a bug... its a feature!  The `--prefix` indicates where things are going to be installed by a `make install`, and `--enable-gambitdir=...` indicates the binding of `~~` at run time.  I could imagine wilder things to do with this flexibility, like binding `~~` to a symbolic link at an absolute location in the file system.  I think it is best to not try to be smart about the link between the two things.

**Comment by lassik** [comment]
OK, works for me!

**Pull request merged**
