### PR TITLE
Implement and test SRFI 141 / R7RS large division procedures

### PR DESCRIPTION
**Pull request by gambiteer**
Marc: I think this could be ready to go; can you look it over?  Brad

### CODE REVIEW

**Comment by feeley** [comment]
Nice! You're coding like a pro! I have little to say, except there are probably some entries missing in the `doc/gambit.txi` file and I'm fairly confident it doesn't pass a `make check` because some files need updating, such as `lib/gambit#.scm` and `lib/gambit/prim/number.sld`, etc.

**Comment by gambiteer** [comment]
It passes `make check` but I'll look at it some more.

**Comment by feeley** [comment]
It passes `make check` because the names `balanced/`, `balanced-quotient`, `balanced-remainder`, etc were added to `lib/r7rs#.scm`.  However this is incorrect because these procedures are not defined by the R7RS standard.  Currently they must be viewed as Gambit specific procedures.  If you remove the new names from `lib/r7rs#.scm` and you do a `make check` the output will guide you to where the names must be added:

```
These names should be ADDED to lib/gambit#.scm:
balanced-quotient
balanced-remainder
balanced/

These names should be ADDED to doc/gambit.txi:
balanced-quotient
balanced-remainder
balanced/

These names should be ADDED to lib/gambit/gambit#.scm:
balanced-quotient
balanced-remainder
balanced/
```

Also, the new names must be added to `lib/gambit/prim/number.sld` and `lib/gambit/prim/number-gambit#.scm` (which is included from `lib/gambit/prim/number#.scm`).  Unit tests must be added to `tests/unit-tests/13-modules/prim_number.scm` (to check for example that `balanced/` has the same behavior as `##balanced/`... see `floor/`).

**Comment by gambiteer** [comment]
You know that declaring the names in all these files by hand is insane, right?

What about adding things to `gsc/_prims.scm`?  All these procedures are basically the same as their `##` versions, does the compiler need to know about them?

I've never written `*.txi`files before, please send me a patch to add the appropriate lines for
```
These names should be ADDED to doc/gambit.txi:
balanced-quotient
balanced-remainder
balanced/
ceiling-quotient
ceiling-remainder
ceiling/
euclidean-quotient
euclidean-remainder
euclidean/
round-quotient
round-remainder
round/
```

**Comment by gambiteer** [comment]
BTW, shouldn't the non `##`-versions in `_prims.scm` of the non-r6rs procedures
```
("bitwise-and"                        0     #f 0     0    integer r6rs)
("##bitwise-and"                      0     #f ()    0    integer extended)
("bitwise-andc1"                      (2)   #f ()    0    integer extended)
("##bitwise-andc1"                    (2)   #f ()    0    integer extended)
("bitwise-andc2"                      (2)   #f ()    0    integer extended)
("##bitwise-andc2"                    (2)   #f ()    0    integer extended)
("bitwise-eqv"                        0     #f 0     0    integer extended)
("##bitwise-eqv"                      0     #f ()    0    integer extended)
("bitwise-ior"                        0     #f 0     0    integer r6rs)
("##bitwise-ior"                      0     #f ()    0    integer extended)
("bitwise-nand"                       (2)   #f ()    0    integer extended)
("##bitwise-nand"                     (2)   #f ()    0    integer extended)
("bitwise-nor"                        (2)   #f ()    0    integer extended)
("##bitwise-nor"                      (2)   #f ()    0    integer extended)
("bitwise-not"                        (1)   #f 0     0    integer r6rs)
("##bitwise-not"                      (1)   #f ()    0    integer extended)
("bitwise-orc1"                       (2)   #f ()    0    integer extended)
("##bitwise-orc1"                     (2)   #f ()    0    integer extended)
("bitwise-orc2"                       (2)   #f ()    0    integer extended)
("##bitwise-orc2"                     (2)   #f ()    0    integer extended)
```
be labeled "gambit" and not "extended"?

**Comment by gambiteer** [comment]
Is there any documentation for `floor-remainder`, etc.?

**Comment by gambiteer** [comment]
Do you have your emacs set up to automatically put in links to previous, next, up, etc., nodes in a `.txi` file?  I feel like I'm doing it by hand in `vi`, very error prone.

**Comment by feeley** [comment]
Nice! Will you implement SRFI 141 in `lib/srfi`?

**Comment by feeley** [comment]
It should be similar to the SRFI 4 implementation.

**Comment by feeley** [comment]
> BTW, shouldn't the non `##`-versions in `_prims.scm` of the non-r6rs procedures
> 
> ```
> ("bitwise-and"                        0     #f 0     0    integer r6rs)
> ("##bitwise-and"                      0     #f ()    0    integer extended)
> ("bitwise-andc1"                      (2)   #f ()    0    integer extended)
> ("##bitwise-andc1"                    (2)   #f ()    0    integer extended)
> ("bitwise-andc2"                      (2)   #f ()    0    integer extended)
> ("##bitwise-andc2"                    (2)   #f ()    0    integer extended)
> ("bitwise-eqv"                        0     #f 0     0    integer extended)
> ("##bitwise-eqv"                      0     #f ()    0    integer extended)
> ("bitwise-ior"                        0     #f 0     0    integer r6rs)
> ("##bitwise-ior"                      0     #f ()    0    integer extended)
> ("bitwise-nand"                       (2)   #f ()    0    integer extended)
> ("##bitwise-nand"                     (2)   #f ()    0    integer extended)
> ("bitwise-nor"                        (2)   #f ()    0    integer extended)
> ("##bitwise-nor"                      (2)   #f ()    0    integer extended)
> ("bitwise-not"                        (1)   #f 0     0    integer r6rs)
> ("##bitwise-not"                      (1)   #f ()    0    integer extended)
> ("bitwise-orc1"                       (2)   #f ()    0    integer extended)
> ("##bitwise-orc1"                     (2)   #f ()    0    integer extended)
> ("bitwise-orc2"                       (2)   #f ()    0    integer extended)
> ("##bitwise-orc2"                     (2)   #f ()    0    integer extended)
> ```
> 
> be labeled "gambit" and not "extended"?

Indeed.

**Comment by lassik** [comment]
> Do you have your emacs set up to automatically put in links to previous, next, up, etc., nodes in a `.txi` file? I feel like I'm doing it by hand in `vi`, very error prone.

It's really labor intensive and error prone to get them right by hand. Emacs has `M-x texinfo-all-menus-update` to do it.

**Pull request merged**
