### PR TITLE
Fix issues with delete-directory on Windows, and misbehaving hypot on…

### PR DESCRIPTION
**Pull request by feeley**
… MinGW

### CODE REVIEW

**Comment by lassik** [comment]
From the commit:

> On Windows, a call to RemoveDirectory doesn't immediately delete the directory. Instead the directory is marked for deletion, so it is necessary to busy-wait for the OS to actually delete it. Unfortunately, this introduces a race condition where some other process may be creating a file or directory with the same name. A better solution would be to move the directory to a safe place with a unique name and then call RemoveDirectory on it.

MSDN says:

> The RemoveDirectory function marks a directory for deletion on close. Therefore, the directory is not removed until the last handle to the directory is closed.

So the issue is whether or not some process has the directory open. I don't think it's possible to move a file/directory when there are open handles to it, so moving the directory to a safe place may not be possible either.

**Comment by lassik** [comment]
To be clear, on Unix `rename()` works despite open handles, but on Windows it doesn't IIRC.

**Comment by feeley** [comment]
This idea comes from a youtube video of a Windows developer saying this is the only correct implementation (moving then deleting the directory) and he has implemented it that way.  See https://www.youtube.com/watch?v=uhRWMGBjlO8 at 7:40.

**Comment by lassik** [comment]
Thanks, very interesting. Apparently it's possible to open files using a special mode that doesn't forbid others from moving their directory entries from underneath them (i.e. mimic Unix). I didn't understand from the video whether that's the only situation due to which the presenter is doing that temp rename thing, but it's surely better to follow his advice than mine.

**Pull request merged**
